# Generated by Django 3.1.7 on 2021-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210324_1324'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='account',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='api.Contest'),
        ),
    ]
